### ISSUE TITLE
New line wrong indention

### ISSUE THREAD

**Issue by jgrzebyta** [jeeger/ttl-mode#1]
There are following problems with indention:

```
:test    a     :Foo  ;
                 rdfs:label "This is simple Foo class " ;    <--- new line started in wrong place
                 owl:VersionInfo "0.0.1" .
```

**Comment by jeeger** [comment]
Cannot reproduce here. The "<--- new line " comment leads to incorrect indentation, but if I insert a comment marker, it looks correct.
![screenshot](https://user-images.githubusercontent.com/3542252/53189497-eff51c80-3607-11e9-873c-f95c0ea1120a.jpg)

**Comment by jeeger** [comment]
What is the problem? That the line with `rdfs:label` is indented so deeply? This shouldn't happen, did you change `ttl-indent-width`? Or are you using tabs for indentation?

The mode does not *align* things (like aligning the `rdfs:label` with the `a`), it indents them to a fixed depth.

**Comment by jgrzebyta** [comment]
I found I was my mistake. The indention is fixed in emacs.
