### ISSUE TITLE
Not able to put dot in string in a blank node

### ISSUE THREAD

**Issue by jgrzebyta** [jeeger/ttl-mode#3]
I had following turtle:
```
rml:logicalSource [
   rml:source "http://www" 
];
```
When I try to put dot '.' following 'www' I had error message: "No period in blank nodes".

**Comment by jeeger** [comment]
Hello! Thanks for the report, that was indeed a bug! It should be fixed in 001d815679896d566e513c858d3e8a8af51a5308.
