### ISSUE TITLE
auto-complete prefixes

### ISSUE THREAD

**Issue by VladimirAlexiev** [jeeger/ttl-mode#7]
As you see in #6, FIBO prefixes are numerous, multi-worded and hard to remember.
There are 100-200 of them, and neither is in http://prefix.cc because that site does not accept multi-word prefixes.
- read prefixes from the current file and from file `prefixes.tll`
- use some auto-completion mechanism to complete a prefix at point (eg after `tr-` or `fibo-`). It should show the corresponding URLs so I can select the right one.

**Comment by jeeger** [comment]
This is currently not in the cards, as it would require extensive work. I'd of course welcome patches!
